# Permalinks
permalink:           pretty

# Setup
title:
  en: "hitmany blog"
  ru: "Блог hitmany"
#
tagline:
  en: "My notes about everything"
  ru: "Мои заметки обо всем"
#
url:                 http://hitmany.net
paginate:            2
baseurl:             "/blog"
index:
  en:
  ru: glavnaya.html
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              hitmany
  url:               http://hitmany.net
  email:             hitmany@hitmany.net

# Custom vars
version:             2.0.0
encoding: utf-8
github:
  repo:              https://github.com/hitmany/hitmany.github.io/tree/master/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
#highlht
highlighter: pygments
paginate:         10
menulist:
  en:
    home:
      name: "hitmany blog"
      url: "/blog/"
    about:
      name: "About"
      url: "/blog/about"
    archive:
      name: "Archive"
      url: "/blog/archive"
    feed:
      name: "Feed"
      url: "/blog/atom.xml"
  ru:
    home:
      name: "Блог hitmany"
      url: "/blog/glavnaya"
    about:
      name: "О блоге"
      url: "/blog/obloge"
    archive:
      name: "Архив"
      url: "/blog/archive"
    feed:
      name: "Лента"
      url: "/blog/atom.xml"